spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ecommerce_db
    username: root
    password: password
  data:
    redis:
      host: localhost
      port: 6379
  jackson:
    find-and-add-modules: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

app:
  jwt:
    secret: 0uC9dpSqePgOQA3hvRvoTCUJgly1iOqkPoImkCGxVeVKku9nSih3gner8w1IvfhUaIEGjhSZRQdle5zDsRU4Xz
    access-token-expiration-ms: 86400000
    refresh-token-expiration-ms: 86400000

openapi:
  service:
    api-docs: api-service
    server: http://localhost:8080
    title: API Service
    version: 1.0.0

outbound:
  oauth2:
    client:
      registration:
        google:
          clientId: 267032846386-hchqmc5j59qi1ti287asu2bgb9fafqk1.apps.googleusercontent.com
          clientSecret: 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
          redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
          scope:
            - email
            - profile
        facebook:
          clientId: 121189305185277
          clientSecret: 42ffe5aa7379e8326387e0fe16f34132
          redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
          scope:
            - email
            - public_profile
        github:
          clientId: d3e47fc2ddd966fa4352
          clientSecret: 3bc0f6b8332f93076354c2a5bada2f5a05aea60d
          redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
          scope:
            - user:email
            - read:user
      provider:
        facebook:
          authorizationUri: https://www.facebook.com/v3.0/dialog/oauth
          tokenUri: https://graph.facebook.com/v3.0/oauth/access_token
          userInfoUri: https://graph.facebook.com/v3.0/me?fields=id,first_name,middle_name,last_name,name,email,verified,is_verified,picture.width(250).height(250)
