spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ecommerce_db
    username: root
    password: password
  data:
    redis:
      host: localhost
      port: 6379
  jackson:
    find-and-add-modules: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  cloudinary:
    api:
      name: ${CLOUDINARY_NAME}
      secret: ${CLOUDINARY_SECRET}
      key: ${CLOUDINARY_KEY}

app:
  name: ecommerce-dev
  clientUrl:
    backoffice: http://localhost:5173
    storefront: http://localhost:3000
  upload:
    location: cloudinary
  jwt:
    secret: ${JWT_SECRET}
    access-token-expiration-ms: 60000
    refresh-token-expiration-ms: 86400000
  frontendErrorUrl: ${CLIENT_URL}/400
  oauth2:
    google:
      clientId: ${GOOGLE_CLIENT_ID}
      clientSecret: ${GOOGLE_CLIENT_SECRET}
      redirectUri: ${CLIENT_URL}/oauth2/callback/google
      scope:
        - email
        - profile

    facebook:
      clientId: ${FACEBOOK_CLIENT_ID}
      clientSecret: ${FACEBOOK_CLIENT_SECRET}
      redirectUri: ${CLIENT_URL}/oauth2/callback/facebook
      scope:
        - email
        - public_profile

    github:
      clientId: ${GITHUB_CLIENT_ID}
      clientSecret: ${GITHUB_CLIENT_SECRET}
      redirectUri: ${CLIENT_URL}/oauth2/callback/github
      scope:
        - user:email
        - read:user
openapi:
  service:
    api-docs: api-service
    server: http://localhost:8080
    title: API Service
    version: 1.0.0


