package com.yas.system.auth.internal.mfa;

public interface MfaService {
    
    /**
     * Generates a new MFA secret key for the given user.
     * Use this during the initial MFA setup to obtain a secret 
     * that can be presented as a QR code to the user.
     *
     * Example Usage:
     *   String secret = mfaService.generateMfaSecret("john.doe@example.com");
     *   user.setMfaSecret(secret);
     *   userRepository.save(user);
     * 
     * @param email The user's email or unique identifier.
     * @return A generated Base32 secret string.
     */
    String generateMfaSecret(String email);

    /**
     * Validates the provided TOTP (Time-based One-Time Password) code against the user's secret.
     * This function should be called during login to verify the 2FA token
     * generated by the user's authenticator app against the mfaSecret stored in the entity.
     *
     * Example Usage:
     *   boolean isValid = mfaService.verifyTotpCode(user.getMfaSecret(), "123456");
     *   if (!isValid) throw new BadCredentialsException("Invalid MFA code");
     * 
     * @param secret The MFA secret key stored in the user's entity.
     * @param code The numeric TOTP code entered by the user.
     * @return true if the code is valid, false otherwise.
     */
    boolean verifyTotpCode(String secret, String code);

    /**
     * Generates a QR code URI that can be rendered on the frontend.
     *
     * Example Usage:
     *   String uri = mfaService.generateQrCodeUri(user.getEmail(), secret, "689Cloud");
     *   // Return `uri` to the frontend, which will use a library like qrcode.react to display the QR Code.
     * 
     * @param email The user's email.
     * @param secret The generated MFA secret.
     * @param issuer The name of the application (e.g., 689Cloud).
     * @return String representation of the QR code URI.
     */
    String generateQrCodeUri(String email, String secret, String issuer);
}
